# Calculate the mean and variance
 Mean = sqrt(a_hat_t) + x0
 
 Variance = sqrt(1-a_hat_t) * random_noise

In [2]:
%pip install torch

  Obtaining dependency information for torch from https://files.pythonhosted.org/packages/1e/86/477ec85bf1f122931f00a2f3889ed9322c091497415a563291ffc119dacc/torch-2.1.2-cp311-none-macosx_11_0_arm64.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 MB 13.9 MB/s eta 0:00:00m eta 0:00:010:00:01
Note: you may need to restart the kernel to use updated packages.


In [3]:
import torch

In [4]:
x0 = torch.randn(2,3,32,32)

In [25]:
x0.size()

torch.Size([2, 3, 32, 32])

In [13]:
t = torch.tensor([1,3])

In [17]:
t.size()

torch.Size([2])

In [10]:
betas = torch.tensor([0.05,0.1,0.15,0.2,0.25])

In [15]:
betas

tensor([0.0500, 0.1000, 0.1500, 0.2000, 0.2500])

In [11]:
# betas → amount of noise that are being applied at every timestep of the diffusion process

In [12]:
alphas = 1 - betas

In [31]:
# alphas → amount of original image information that is being preserved after a diffusion process

In [16]:
alphas

tensor([0.9500, 0.9000, 0.8500, 0.8000, 0.7500])

In [18]:
alpha_hat = torch.cumprod(alphas, axis=0)

In [19]:
alpha_hat

tensor([0.9500, 0.8550, 0.7268, 0.5814, 0.4360])

In [20]:
result = alpha_hat.gather(-1, t).reshape(-1,1,1,1)

In [24]:
result.size()

torch.Size([2, 1, 1, 1])

In [27]:
#result → we are reshaping the alpha_hat in the dimension of x0

In [28]:
noise = torch.rand_like(x0)

In [30]:
noise.size()

torch.Size([2, 3, 32, 32])

In [32]:
# Calculation of mean
mean = result.sqrt() + x0

# Calculation of variance
variance = torch.sqrt( 1 - result )*noise

In [35]:
x_t = mean + variance

In [38]:
#First image at timestep t
x_t[0]

tensor([[[ 1.8103,  1.6472,  3.0666,  ..., -1.0779, -1.0634,  1.7593],
         [ 1.5921,  1.9702,  0.6590,  ...,  0.8590,  0.7861,  0.5062],
         [ 1.8802, -0.5000, -0.0795,  ...,  0.8281,  0.6196,  1.1816],
         ...,
         [-0.5355,  0.8707,  2.6897,  ...,  1.0464,  2.5198, -0.5387],
         [ 1.4952,  1.3427,  0.9649,  ...,  1.5111,  1.7523,  0.0743],
         [ 2.1193,  1.2659,  0.3731,  ...,  0.1963,  1.1292,  1.5549]],

        [[-0.3293,  1.8732,  0.1629,  ...,  1.6224, -0.2687,  0.8724],
         [ 1.7015,  0.4258,  0.8971,  ...,  2.6184,  0.1171,  1.3927],
         [ 0.2548,  1.1410,  0.8644,  ...,  0.3495, -0.1510,  2.1311],
         ...,
         [ 2.9619,  1.0646,  2.9761,  ...,  1.6521,  0.2798,  1.4982],
         [ 1.0184,  1.7888,  1.7942,  ..., -0.3556, -0.2690,  0.1939],
         [ 0.9236, -0.6100,  0.2650,  ...,  0.8967,  0.5792,  1.3118]],

        [[ 1.9463,  1.5102,  0.8515,  ...,  1.8449,  1.8115,  0.9801],
         [ 0.5054,  1.2875,  0.9433,  ...,  0

In [39]:
#Second image at timestep t
x_t[1]

tensor([[[ 0.2941,  1.8733,  1.5471,  ...,  0.0845,  0.4996, -0.0220],
         [ 1.9915,  0.1635,  0.1234,  ...,  1.1023,  1.2290,  1.1644],
         [ 0.9797,  2.3863, -0.4507,  ...,  3.7916, -0.4039,  0.4625],
         ...,
         [ 0.6933,  0.7798,  2.2762,  ..., -0.4889, -0.5221,  0.3263],
         [ 0.5038,  0.0820,  0.8328,  ...,  1.7976,  2.2684, -0.0823],
         [ 0.9026,  1.0528, -0.4878,  ...,  0.7485,  0.3657,  1.3284]],

        [[ 1.9576,  0.3182,  3.7878,  ...,  1.4561,  0.6093,  3.0948],
         [ 1.2906,  0.9960,  1.9799,  ...,  0.9066,  0.9593,  1.2625],
         [ 1.7193,  1.8952,  2.5678,  ...,  1.4027, -0.5155,  2.0632],
         ...,
         [ 0.3575, -0.4833,  0.4658,  ...,  1.6573,  1.4969,  2.2261],
         [ 1.2979, -0.6047,  0.2643,  ...,  2.0538,  2.3118,  0.3647],
         [ 1.4946,  2.4862,  0.1686,  ..., -0.8368,  2.4225,  1.3607]],

        [[-0.7443,  0.2464,  1.1697,  ..., -0.0723,  1.8251,  1.3743],
         [ 0.6812,  1.0409,  1.7015,  ...,  1